language: scala

scala: 2.12.8

jdk: openjdk8

before_install:
- "[ -z \"${encrypted_44858260af60_iv}\" ] || openssl aes-256-cbc -K $encrypted_44858260af60_key -iv $encrypted_44858260af60_iv -in ./project/zecret -out ./project/secret -d"
- git fetch --tags

env:
  global:
  # USER
  - secure: "hznBXMHp4gwbGTBQWRZHy2vXkR5YZ+1NF/yruU+C/bg9BtY+3Ishet+jTw5qc+Ptbv1jLP1lS/ckJX6r5aex14bAjlWcTtiXqyelOIRAV+8TmHbGi5OTpIIhKGSqw0ef5qb2b0kacmtqBAzx7Vy/wD2taIFfs7KBRWnBdVmsNGFfVE5icyvIYLsHueOUM4ceshapa2TjNb65QMw0sdQRESKUmbCcm5lhw39/PMwOrw3t5odFt7aVHBgHLA65Om4E6bXt/1q42Byf57jui3n+XODMDa2DTgn7iSz1AWCt/X/Sxr2HmZjELsC2W6erH/U48lsdKofRIkIIVxARAAqPsUKuJHkFok0/mUbJXsGyfInpdyjpyoonbNXK3WDgrjqdNKtnZZLLhauRAjSQDs7iVNAgg4NCrSZ6YvFm2VIaULxGuc31WVStPD8rPeAdHb1K2vYH91TXNxeFgfWYY/Lz9kV1o81q+5lyz4eJUU2a/U2urVGiar4znWuNaAUswrkKsxMOTD/cZ+5Ca/RQhvYM2/5ez5v6qOIaOSaaSQ218YFxh1UhLEVuzUZE98FJryrBiSkK0+IgA116TQWOeReh4ZcP6ILJX8Ozsm/WPNJac2t/x8Qd2mK3YlaggBoY/XXfMzH1X93nEP4KXqpF6ZmbfsBs7TfSikujsK3XM/NmLsc="
  # PASS
  - secure: "BV/nbiemNtAoTb3wFX9wCsu5cMKjZVgcBJmpYtNt3M4yBr81Cs4wNtlz/4PZInnJcr2klbzy7qhrOvswK+VEqpGdxi6pf9P8Yrn0WBJ3ob6jEdlAWIOpMOMYRbUQgIM7WHRsOKgqR42TU1uy7dMqowYODjWCPUD1FrAFHGhu5D1smF7PVNQ15dMw3C1hTB8oj4+qMD8hUEOels03OrDm2+iaBdXuKvN0ha72zzR5zs+gqaWE+PRRJYlQn8Mrjbb62qv4dsEDZObyhtNgCKBtaBV4LgwAhUAZMv1n33Qdmx4TCmNAiOWvLkgIl8KezTEIds+HY3B5cMTzaHd/BwVw9CM+AQ88mKvmh/6UyWWVkpboUYsuyFPnDsgoFLjvFuaxieOjgc6PkhWMFDENdqezRAWcCKDSR8uxlP0XKh5E4WMCax8XoCZHB3BWKHSmzKVHtLMAgLLLUnXg7dLO+n1QPlXJMfl5Nhl6q5IQhMFw/k0sleOONxOkheU89wBTK8/xl5MXNmhh6KR3UwL8CPGgHVsbcNAL2W9YYOuggdvLY6EM2LUfT9zyDXac5nkIUaepQ+7Ud682ZjQltEHnNUpBt595436ij4qzXnSZiRBjylAgKd7DGs8NLvNcyIMHBpu7NzpbPmeuJQac37TBtky2D0N4wvT7PaY3v6k38Puj4JU="
  # PGP
  - secure: "HzaGyQK/B3ILfL3cMGqHh4BrOWd94IoMPG3Eelu8bzENn6aHTHJQkLC9lxKTeqx5l/so7wP4+jm995rYIiIk0T8hJCc7eZEXvyhuSwPghRS9IOaMUe9qLiZJnmJX5/uKTAbSafWmKBEKQ2iw+b7F3U5zy2NMxbHvjAdyg8Reai08xJX0bmT+vtNk1t72rm16cLVilBaH++AwQWW5zPOSyJCQqblllLSjnxTmgnLKdobTXCJf+9m2jJ/cw/0cHva7zgXRSeFa30E7ILM9yKNenrvZN4M9W3OBjb7QWbi9PO/YoikDNRZI1WNzaBiyNHqcG3yQGNKPpUcym22Sbv+fDXf7UseKXMiNrJMunDDZqelfDYZGmf0+M9sPj1nPueNGObrwiV9DPnUEODdmMyJ54+IHUvTtmQdNvjUHYbo+EzD7xOsgSXfgJR/rwECmLJE6MAorFIZtdr4smwl+IjsRlMdA/wBOk2+EXcT4BLPq+SMIN0LWUha0nssoBSDaz6iPTvup46KEjgeGdYh/PyJbmcNG+EpoiCTxDJSY3A5filJsS2pY3XeWWsp8tdK18J8tAZSc4iw6E9HTQ1RNcsQpCDLk2j4wpFEsv+6Lor8Dpx6iQKkfiJPA+ldrrxDLl2q6P8N+yN5VNEOd/T4t3oApC0HZQxuliDdpPVYXEbkR0wQ="

stages:
- name: lint
- name: build
- name: release
  if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - &lint
      stage: lint
      name: "Lint"
      script: sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &build
      stage: build
      name: "Build (JDK8, 2.12)"
      script: sbt ++$TRAVIS_SCALA_VERSION! test
    - &release
      stage: release
      name: "Release artifacts"
      before_script: export PGP_SECRET="$(<./project/secret)"
      script: sbt ci-release || sbt sonatypeReleaseAll

    - <<: *build
      jdk: openjdk11
      name: "Build (JDK11, 2.12)"
    - <<: *build
      scala: 2.11.12
      name: "Build (JDK8, 2.11)"
    - <<: *build
      jdk: openjdk11
      scala: 2.11.12
      name: "Build (JDK11, 2.11)"
    - <<: *build
      scala: 2.13.0-M5
      name: "Build (JDK8, 2.13)"
    - <<: *build
      jdk: openjdk11
      scala: 2.13.0-M5
      name: "Build (JDK11, 2.13)"
