language: scala

scala: 2.12.7

jdk: openjdk8

before_install:
- "[ -z \"${encrypted_44858260af60_iv}\" ] || openssl aes-256-cbc -K $encrypted_44858260af60_key -iv $encrypted_44858260af60_iv -in ./project/zecret -out ./project/secret -d"
- git fetch --tags

env:
  global:
  - secure: "bmkXi1oBjcu6hvewAQuxVAyqYVp/S1JpKAWmvyUVq4Ufu24DGlZXkKpxHdEVasM4j9ztANd7o/0wlO0WLKgRQMrEfc+Zv7mVs24LCDFCINhGjNKjFNir+NmwnBboCbw8Lo5vkd22Jp9LNLykCM83ytCz68EHvBEuTIGrk+v9aSO4ff2sJ4ZYpzcPN2xptXz0hVGFPPvE+5yIogRtMgDVi7Vs8iHmaOP1+MP4IVH5Tsm+nUB9q48ZFBYj80dmecPBIFlIiNXRbWwUYIypqJP9Q6NJ4Dgshm1qCDJvJOtCiah84NIYKs7XZJmI6ufztXOivXJcKBPGs+gAiQ3q6fNcfPjS8V1yizx147UlqeyCBdXWLbZLuCTMwhBe03Ad1VzKdS6CY1ysWe6C5ZYJpPCw9Jhw9MO1huQWQRfiig7A8ZR4WEZ5xjRYgwjyJ13UPe+jI7AzA40H50wFh+EFdX62Et7sLoVu/+pf4vCfo1SGo/VdmZWTev0CcfUZH7w0WAvxBn/9iI3EkYcPdjQMurY2dXWdyfCMyCdodDEMrpzLkalFwU1lCyv2FG8IjVC+cYtD7MAhz3QTJUsEwtA6DUYxkTz3n9gontr8aXwGayOHnhq7Nywg06eCuAKEfSeAthpfjpv32YChZ1zkbkRAOt4GewkSd4WDPHOrYsDMfDpkHZI="
  - secure: "mN1NrKrfhMoXLM0mEGUiTrZD/UVZ9YDgsuzb8Un58qeYIA5jvSYtiuy7YtmAtMX1OCyLgm7bMh4h+JBSZf4K3YjgDqynSSCAHciL04W6gBCrtdVWRxEMCcv639+yRJx6As/1y8RPZfwLyJunaa5Xj0abOUj/xNN7MDxzLroCIDM/ILAqpyVdGkqMNKOo/WMZJINxulssHNFr8icOL4+JeYTrW6cVtp0Wn8HIm5GOchY08T4SKVRVyAyCs+7QH0Syqy0C0dgYDB2eUjYQoF1krtAGeQqJ+zOrW5fBUkCljtwOTKEu1wJcy5uaIgS3AycJEgFOOPIbdN7M6KzOuA5iREMzSV5D7QzJ8LGbH4H3Vr7ZpK1Fm0kbqOb/AEAFfsAaZHnyroAJpIh8tUOBs7J3lFzrwLk1ZH+BpLu3AJ0zootkT+RTRc62Ylpil4btMSSItjZYVt5DWryHBm21XFy3cba32ZY4Bb3rBr+2qf4rIKPOueAxqWwPo+WmCZ84BjDnP+JyAGa1yZnqK/lUyu29XmTCd31l/xDyC9sPQQgvXtfHe+lxvne2dSfmhs6vaNKD+iyJcnF58je2Ilaer5Em3lZ4Z272R7sr11jcgxwhfjivDji3rGCcySfClA0btgpuLXWKJPGfrwcNAZy4YkfaRvQuF/KLETdGir0cszlgjAw="
  - secure: "rpX9L6CKekBhmLWcq1ixRKvKkig92C3FDPtThYoM5kp5UqeTp0fNt3danLVODA8ABzbg7CEODgxymUOtcuDafWdOiV3wfSt1EBkA2i0CUzB/CBBpbFewQlTHnuB5+UrIUOKZ/4QyKuMiZeiaFfvA64Oqyxb3qN5QbJDpSYA5R5Zu7v8r+plVr4vXASdjqgkkYo3igkQWCMOJh11V3tTaDbtO2RHLsOWtUeqJh0s4W6HpGVCbqBYL10Ik4By/s7CPKT+mujdxs2UH09FoBo8/y4O+sgfitTGj4BYxzrhiWEKMc1b1fe1QXjx7pwMR4gsgYWuP/4t7PF+A/Dx93yranzdH5m96iX3DoYvKhMFkBJ1Ciu+E/n32wM/DMoD8pzcg+5PhjfNGxFBOc2x723JsRcU9NsyEbrWg2nUTyd6n4puuUuJvM9NVPO5xuSdR8dwO29NhIaXJPBazcZOXcSmhAO/7nKuDT5lw7UrlZ9hHGI2HddOQLrCnGVZP8Ywt3Xocj77Y1238e6EK8qCPxmdoYmvX5hx3/8v8LwSK8VL9bHH987llgoDIDgZtng/YbgupHAetfnv5Eq30Whk5gLJxElA2HMyc07K4YYD/RuX228HgicVL7PS5P4eQoUKChfNUuPT5jzONdrlTrqu+EELGaxhnPYBF9Qz/xw4azOfnKQ0="

stages:
- name: lint
- name: build
- name: release
  if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - &lint
      stage: lint
      name: "Lint"
      script: sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &build
      stage: build
      name: "Build (JDK8, 2.12)"
      script: sbt ++$TRAVIS_SCALA_VERSION! coverage test coverageReport
      after_success: bash <(curl -s https://codecov.io/bash)
    - &release
      stage: release
      name: "Release artifacts"
      before_script: export PGP_SECRET="$(<./project/secret)"
      script: sbt ci-release || sbt sonatypeReleaseAll

    - <<: *build
      jdk: openjdk11
      name: "Build (JDK11, 2.12)"
    - <<: *build
      scala: 2.11.12
      name: "Build (JDK8, 2.11)"
    - <<: *build
      jdk: openjdk11
      scala: 2.11.12
      name: "Build (JDK11, 2.11)"
